Bump com.github.siom79.japicmp:japicmp-maven-plugin from 0.25.4 to 0.25.5 (#390)
Bumps
[com.github.siom79.japicmp:japicmp-maven-plugin](https://github.com/siom79/japicmp)
from 0.25.4 to 0.25.5.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/siom79/japicmp/releases">com.github.siom79.japicmp:japicmp-maven-plugin's
releases</a>.</em></p>
<blockquote>
<h2>japicmp-base-0.25.5</h2>
<h2>0.25.5 (2026-04-09)</h2>
<ul>
<li>getAnnotations() no longer returns empty list in case of removed
members <a
href="https://redirect.github.com/siom79/japicmp/issues/497">#497</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/siom79/japicmp/commit/b2298f36670d230356bf4d9daae4e8ba15346777"><code>b2298f3</code></a>
[maven-release-plugin] prepare release japicmp-base-0.25.5</li>
<li><a
href="https://github.com/siom79/japicmp/commit/405115f3cbfce477826cf3d86b579c07d8e64254"><code>405115f</code></a>
upgraded version in *.md files to 0.25.5</li>
<li><a
href="https://github.com/siom79/japicmp/commit/981f6275213d9f338a6f059478a8ec8a2cc30d84"><code>981f627</code></a>
Add release notes for version 0.25.5</li>
<li><a
href="https://github.com/siom79/japicmp/commit/2ba4beea9b95978116eb2ff83e81386b11fde404"><code>2ba4bee</code></a>
Merge pull request <a
href="https://redirect.github.com/siom79/japicmp/issues/498">#498</a>
from siom79/claude/fix-removed-annotations-fQAHT</li>
<li><a
href="https://github.com/siom79/japicmp/commit/f4a7c477c0886f1ae505e3c923e787322f0a39e0"><code>f4a7c47</code></a>
Fix compilation error: remove invalid publicAccess() call on
CtFieldBuilder</li>
<li><a
href="https://github.com/siom79/japicmp/commit/862c9fa5b054a9d0a118d91fd5c0ffbef5f57b28"><code>862c9fa</code></a>
Fix getAnnotations() returning empty list for removed members</li>
<li><a
href="https://github.com/siom79/japicmp/commit/0baa5312cc0f138ce16098d751c74d5dca0a9214"><code>0baa531</code></a>
Merge pull request <a
href="https://redirect.github.com/siom79/japicmp/issues/495">#495</a>
from bradleylarrick/implement-cangeneratereport</li>
<li><a
href="https://github.com/siom79/japicmp/commit/8d8b23b54f6dec1366f1682ce5e3be0bf7d5f01a"><code>8d8b23b</code></a>
Merge pull request <a
href="https://redirect.github.com/siom79/japicmp/issues/493">#493</a>
from bradleylarrick/plugin-unit-tests</li>
<li><a
href="https://github.com/siom79/japicmp/commit/d0d8897893e03eac7df2a912cf7142fa9a9029b2"><code>d0d8897</code></a>
Implemented canGenerateReport() method in Report mojo.</li>
<li><a
href="https://github.com/siom79/japicmp/commit/fd0ea30c7fc074db90645e22adee1258c61ad652"><code>fd0ea30</code></a>
Removed commented-out code; moved property expansion code to separate
method.</li>
<li>Additional commits viewable in <a
href="https://github.com/siom79/japicmp/compare/japicmp-base-0.25.4...japicmp-base-0.25.5">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.github.siom79.japicmp:japicmp-maven-plugin&package-manager=maven&previous-version=0.25.4&new-version=0.25.5)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>