Add workaround to deal with ApexLink initialization errors
These are ExceptionInInitializerError and NoClassDefFoundError

It basically won't work without changes in eclipse equinox, which
provides uris like "bundleresource://..." from the class loader.
ApexLink uses Class.getResource(...) to find all pseudo Apex
classes on the classpath (all classes under package "com.nawforce.runforce".

See https://github.com/nawforce/apex-link/blob/7688adcb7a2d7f8aa28d0618ffb2a3aa81151858/apexlink/src/main/scala/com/nawforce/apexlink/types/platform/PlatformTypeDeclaration.scala#L260-L273